# Generated by Django 5.0.2 on 2024-02-17 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_profile_alter_recipe_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.user'),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferred_recipes',
            field=models.ManyToManyField(blank=True, related_name='preferred_by', to='api.recipe'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='api.user'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='used_in_recipes', to='api.ingredient'),
        ),
    ]
