# Generated by Django 5.0.2 on 2024-02-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ingredient_user_profile_preferred_recipes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favorite_ingredients',
            field=models.ManyToManyField(blank=True, related_name='favored_by', to='api.ingredient'),
        ),
    ]
