version: 2.1

orbs:
  win: circleci/windows@5.0.3

jobs:
  build:
    executor:
      name: win/default
      size: 'medium'
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            choco install nodejs --version 18.14.0
            npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Build the project
          command: npm run build

workflows:
  version: 2
  build-and-test:
    jobs:
      - build