version: 2.1
jobs:
  build_test:
    docker:
      - image: circleci/node:21
    steps:
      - checkout
      - run: 
          name: Install npm dependencies
          command: |
            npm install --save
  build_docker_image:
    docker:
      - image: circleci/node:21
    steps:
      - checkout
      - setup_remote_docker: 
          docker_layer_caching: false
      - run:
          name: Build Docker image
          command: |
            docker build -t recipeek -t sarthaktejale/recipeek:tagname .
            echo $DOCKER_PASSWORD | docker login -u sarthaktejale --password-stdin
            docker push sarthaktejale/recipeek:tagname

workflows:
  build_test:
    jobs:
      - build_test
      - builder_docker_image