version: 2.1
jobs:
  build:
    docker:
      -image: circleci/node.20.11.1

  steps:
    -checkout

    run: 
      name: Install npm dependencies
      command: |
        npm install --save
  build_docker_image:
    docker:
      -image: circleci/node:20.11.1
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: false
      - run:
          name: Build Docker image
            command

