name: CI

on: [push, pull_request]

jobs:
  frontend-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - name: Install frontend dependencies
      run: npm install
      working-directory: ./frontend

    - name: Run frontend tests
      run: npm test
      working-directory: ./frontend

  backend-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install backend dependencies
      run: |
        pip install -r requirements.txt
      working-directory: ./backend

    - name: Run backend tests
      run: python manage.py test
      working-directory: ./backend
